# Generated by Django 4.2.3 on 2024-02-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
