# Generated by Django 4.2.3 on 2024-02-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='/static/service_one/images/gruppovaya-terapiya1.jpg', null=True, upload_to='', verbose_name='Картинка на странице услуги'),
        ),
    ]
