# Generated by Django 4.2.3 on 2024-01-20 12:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Отображается на главной страницe.', max_length=40, verbose_name='Заголовок статьи')),
                ('pre_text', models.CharField(help_text='Отображается на главной страницe.', max_length=170, verbose_name='Краткий текст-превью')),
                ('pre_image', models.ImageField(help_text='Отображается на главной страницe.', upload_to='', verbose_name='Картинка-превью')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Основной текст статьи')),
            ],
        ),
    ]
