# Generated by Django 4.2.3 on 2024-01-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Отображается на главной страницe.', max_length=200, verbose_name='Заголовок статьи'),
        ),
    ]
