# Generated by Django 4.2.3 on 2024-01-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Можно поставить любое', max_length=100, verbose_name='Название настройки')),
                ('slug', models.SlugField(help_text='Используется в коде. Нельзя изменять!', max_length=30, verbose_name='Слаг. Не трогать!')),
                ('value', models.CharField(blank=True, help_text='Если это номер телефона, то: +79315663388', max_length=400, null=True, verbose_name='Значение')),
            ],
        ),
    ]
